name: loveconf
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # Firebase
  firebase_core: ^3.6.0
  cloud_firestore: ^5.6.12
  
  # Permissões
  permission_handler: ^11.3.1
  
  # Utilitários
  clipboard: ^0.1.3
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  
  # Localização
  geolocator: ^11.0.0
  geocoding: ^3.0.0
  
  # Mapas
  google_maps_flutter: ^2.6.0
  
  # Notificações Push
  firebase_messaging: ^15.2.10
  flutter_local_notifications: ^17.2.2
  
  # Exportação
  path_provider: ^2.1.3
  share_plus: ^7.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
